const BREAKPOINT1 = 640;
const BREAKPOINT2 = 1024;
const BREAKPOINT3 = 1280;
const GOOGLE_MAPS_PLACE_ID = 'ChIJKWHkknSkrhIRyr5qMV_LHnY';

export { BREAKPOINT1, BREAKPOINT2, BREAKPOINT3, GOOGLE_MAPS_PLACE_ID };
