const BREAKPOINT_1 = 640;
const BREAKPOINT_2 = 1024;
const BREAKPOINT_3 = 1280;
const GOOGLE_MAPS_PLACE_ID = 'ChIJKWHkknSkrhIRyr5qMV_LHnY';

export { BREAKPOINT_1, BREAKPOINT_2, BREAKPOINT_3, GOOGLE_MAPS_PLACE_ID };
