name: Pull Request

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Start deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ secrets.RECALL2_BOT_PAT }}
          environment: prelive
          ref: develop

      - name: Deploy to Vercel
        run: echo ok

      - name: Update deployment status (success)
        if: always() && !failure() && !cancelled()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.RECALL2_BOT_PAT }}
          state: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.RECALL2_BOT_PAT }}
          state: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
